apps/nectar/web/router.ex
defmodule Nectar.Router do
  use Nectar.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :api_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :admin_browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
    plug Nectar.Plugs.AdminAccessRequired
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
  end

  scope "/", Nectar do

    pipe_through [:browser, :browser_auth] # Use the default browser stack

    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/sessions", SessionController, only: [:new, :create]
    delete "/logout", SessionController, :logout

    resources "/orders", OrderController, only: [:index, :show]

  end

  # all actions where the user's cart is required go here.
  # note: if cart is not present it will create and link a new one.
  scope "/", Nectar do
    pipe_through [:browser, :browser_auth, Nectar.Plugs.Cart]
    get "/", ProductController, :index, as: :home

    get "/cart", CartController, :show
    put "/cart", CartController, :update

    resources "/products", ProductController, only: [:show, :index]
    resources "/line_items", LineItemController, only: [:create, :delete]
    get "/checkout",      CheckoutController, :checkout
    put "/checkout/next", CheckoutController, :next
    put "/checkout/back", CheckoutController, :back
    resources "/categories", CategoryController do
      get "/products", CategoryController, :associated_products, as: :products
    end
  end

  scope "/admin", Nectar.Admin, as: :admin do
    pipe_through [:browser, :admin_browser_auth]

    get "/", HomeController, :index
    resources "/countries", CountryController do
      resources "/states", StateController, only: [:create, :delete]
    end
    resources "/zones", ZoneController do
      resources "/members", ZoneMemberController, only: [:create, :delete]
    end

    resources "/cart", CartController, only: [:new, :edit, :create]

    resources "/categories", CategoryController

    resources "/orders", OrderController, only: [:index, :show, :update, :edit] do
      resources "/line_items", LineItemController, only: [:create, :delete] do
        put "/update_fullfillment", LineItemController, :update_fullfillment
      end
      get "/checkout", CheckoutController, :checkout
      put "/checkout/next", CheckoutController, :next
      put "/checkout/back", CheckoutController, :back
      resources "/payments", PaymentController, only: [:show] do
        put "/refund",  PaymentController, :refund,  as: :refund
        put "/capture", PaymentController, :capture, as: :capture
      end
    end

    resources "/users", UserController do
      get "/all_pending_orders", UserController, :all_pending_orders
    end

    resources "/settings", SettingController, only: [:edit, :update]
    get "/settings/payment", SettingController,  :payment_method_settings
    get "/settings/shipping", SettingController, :shipping_method_settings
    post "/settings/payment", SettingController,  :update_payment_method_settings
    post "/settings/shipping", SettingController, :update_shipping_method_settings

    get "/echo", ChannelEchoController, :echo
    post "/echo", ChannelEchoController, :do_echo


    resources "/option_types", OptionTypeController

    resources "/products", ProductController do
      resources "/variants", VariantController
    end
    resources "/users", UserController
  end

  scope "/api", Nectar.Api do
    pipe_through [:api, :api_auth, Nectar.Plugs.Cart]
    get "/cart", CartController, :show
  end

  use Nectar.RouteExtender
  # Other scopes may use custom stacks.
  # scope "/api", Nectar do
  #   pipe_through :api
  # end
end

apps/nectar/web/views/admin/layout_view.ex
defmodule Nectar.Admin.LayoutView do
  use Nectar.Web, :view

  def active_on_current(%{request_path: path}, path), do: "active"
  def active_on_current(_, _), do: nil

  def active_product_tab(conn) do
    active_on_current(conn, admin_option_type_path(conn, :index)) ||
    active_on_current(conn, admin_category_path(conn, :index)) ||
    active_on_current(conn, admin_product_path(conn, :index))
  end

  def active_country_tab(conn) do
    active_on_current(conn, admin_country_path(conn, :index))
  end

  def active_zone_tab(conn) do
    active_on_current(conn, admin_zone_path(conn, :index)) ||
    active_on_current(conn, admin_zone_path(conn, :new))
  end

  def active_settings_tab(conn) do
    %{request_path: path} = conn
    if path == "/admin/settings/general/edit" do
      "active"
    else
      nil
    end
  end

  def active_orders_tab(conn) do
    active_on_current(conn, admin_order_path(conn, :index)) ||
    active_on_current(conn, admin_cart_path(conn, :new))
  end

  def js_view_name(view_module, view_template) do
    "Admin." <> view_module_name(view_module) <> "." <> view_template_name(view_template)
  end

  defp view_module_name(module_name) do
    module_name
    |> Phoenix.Naming.resource_name
    |> Phoenix.Naming.camelize
  end

  defp view_template_name(template_name) do
    String.replace_suffix(template_name, ".html", "")
  end

end

apps/nectar/web/views/layout_view.ex
defmodule Nectar.LayoutView do
  use Nectar.Web, :view

  def js_view_name(view_module, view_template) do
    view_module_name(view_module) <> "." <> view_template_name(view_template)
  end

  defp view_module_name(module_name) do
    module_name
    |> Phoenix.Naming.resource_name
    |> Phoenix.Naming.camelize
  end

  defp view_template_name(template_name) do
    String.replace_suffix(template_name, ".html", "")
  end

end

apps/nectar/web/templates/layout/_login_nav_bar.html.eex
<nav role="navigation">
  <ul class="nav nav-pills pull-right">
    <li><%= link "Home", to: home_path(@conn, :index) %></li>
    <li><%= link "Products", to: product_path(@conn, :index) %></li>
    <%= if Guardian.Plug.current_resource(@conn) do %>
      <li><%= link "Orders", to: order_path(@conn, :index) %></li>
      <li><%= link "Logout", to: session_path(@conn, :logout), method: :delete, class: "btn btn-danger" %></li>
    <% else %>
      <li><%= link "SignUp", to: registration_path(@conn, :new) %></li>
      <li><%= link "Login", to: session_path(@conn, :new) %></li>
    <% end %>
    <li id="cart" data-cart-link="<%= cart_path(@conn, :show) %>"></li>
  </ul>
</nav>

apps/nectar/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Nectar!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token() %>">
  </head>

  <body data-js-view-name="<%= js_view_name(@view_module, @view_template) %>">
    <div class="container">
      <header class="header">
        <%= render "_login_nav_bar.html", conn: @conn %>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <%= render_existing @view_module, "script.#{@view_template}", assigns %>
  </body>
</html>